[project]
name = "watchdog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Shore", email = "01.amusing_cozies@icloud.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
watchdog = "watchdog:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
